**Import Library**

In [ ]:
import pandas as pd 

In [ ]:
import numpy as np

IMport CSV as DataFarme

In [ ]:
df = pd.read_csv(r'https://github.com/YBI-Foundation/Dataset/raw/main/Fruits.csv')

Get the first five Rows of DataFrame

In [ ]:
df.head()

Fruit Category Fruit Name  Fruit Weight  Fruit Width  Fruit Length  \
0               1      Apple           192          8.4           7.3   
1               1      Apple           180          8.0           6.8   
2               1      Apple           176          7.4           7.2   
3               1      Apple           178          7.1           7.8   
4               1      Apple           172          7.4           7.0   

   Fruit Colour Score  
0                0.55  
1                0.59  
2                0.60  
3                0.92  
4                0.89

Get Information of Dataframe

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Fruit Category      59 non-null     int64  
 1   Fruit Name          59 non-null     object 
 2   Fruit Weight        59 non-null     int64  
 3   Fruit Width         59 non-null     float64
 4   Fruit Length        59 non-null     float64
 5   Fruit Colour Score  59 non-null     float64
dtypes: float64(3), int64(2), object(1)
memory usage: 2.9+ KB


Get Summary Statics

In [ ]:
df.describe()

Fruit Category  Fruit Weight  Fruit Width  Fruit Length  \
count       59.000000     59.000000    59.000000     59.000000   
mean         1.949153    141.796610     7.105085      7.693220   
std          0.775125     67.335951     0.816938      1.361017   
min          1.000000     58.000000     5.800000      4.000000   
25%          1.000000     82.000000     6.600000      7.200000   
50%          2.000000    154.000000     7.200000      7.600000   
75%          3.000000    167.000000     7.500000      8.200000   
max          3.000000    362.000000     9.600000     10.500000   

       Fruit Colour Score  
count           59.000000  
mean             0.762881  
std              0.076857  
min              0.550000  
25%              0.720000  
50%              0.750000  
75%              0.810000  
max              0.930000

GEt Shape Of date frame

In [ ]:
df.shape

(59, 6)

Get Column names

In [ ]:
df.columns

Index(['Fruit Category', 'Fruit Name', 'Fruit Weight', 'Fruit Width',
       'Fruit Length', 'Fruit Colour Score'],
      dtype='object')

Get Unique Values (Class or Label) in y Variable

In [ ]:
df['Fruit Category'].value_counts()

2    24
1    19
3    16
Name: Fruit Category, dtype: int64

In [ ]:
df.groupby('Fruit Category').mean()

Fruit Weight  Fruit Width  Fruit Length  Fruit Colour Score
Fruit Category                                                             
1                 165.052632     7.457895      7.342105            0.783684
2                 170.333333     7.220833      7.195833            0.776250
3                  71.375000     6.512500      8.856250            0.718125

Define y (dependent or label or target variable) and x (independent or features or attribute variable)

In [ ]:
y = df['Fruit Category']

In [ ]:
y.shape

(59,)

In [ ]:
y

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    2
20    2
21    2
22    2
23    2
24    2
25    2
26    2
27    2
28    2
29    2
30    2
31    2
32    2
33    2
34    2
35    2
36    2
37    2
38    2
39    2
40    2
41    2
42    2
43    3
44    3
45    3
46    3
47    3
48    3
49    3
50    3
51    3
52    3
53    3
54    3
55    3
56    3
57    3
58    3
Name: Fruit Category, dtype: int64

In [ ]:
x =df[['Fruit Weight','Fruit Width','Fruit Length','Fruit Colour Score']]

In [ ]:
x.shape

(59, 4)

In [ ]:
x

Fruit Weight  Fruit Width  Fruit Length  Fruit Colour Score
0            192          8.4           7.3                0.55
1            180          8.0           6.8                0.59
2            176          7.4           7.2                0.60
3            178          7.1           7.8                0.92
4            172          7.4           7.0                0.89
5            166          6.9           7.3                0.93
6            172          7.1           7.6                0.92
7            154          7.0           7.1                0.88
8            164          7.3           7.7                0.70
9            152          7.6           7.3                0.69
10           156          7.7           7.1                0.69
11           156          7.6           7.5                0.67
12           168          7.5           7.6                0.73
13           162          7.5           7.1                0.83
14           162          7.4           7.2                0.85
15           160          7.5           7.5                0.86
16           156          7.4           7.4                0.84
17           140          7.3           7.1                0.87
18           170          7.6           7.9                0.88
19            86          6.2           4.7                0.80
20            84          6.0           4.6                0.79
21            80          5.8           4.3                0.77
22            80          5.9           4.3                0.81
23            76          5.8           4.0                0.81
24           342          9.0           9.4                0.75
25           356          9.2           9.2                0.75
26           362          9.6           9.2                0.74
27           204          7.5           9.2                0.77
28           140          6.7           7.1                0.72
29           160          7.0           7.4                0.81
30           158          7.1           7.5                0.79
31           210          7.8           8.0                0.82
32           164          7.2           7.0                0.80
33           190          7.5           8.1                0.74
34           142          7.6           7.8                0.75
35           150          7.1           7.9                0.75
36           160          7.1           7.6                0.76
37           154          7.3           7.3                0.79
38           158          7.2           7.8                0.77
39           144          6.8           7.4                0.75
40           154          7.1           7.5                0.78
41           180          7.6           8.2                0.79
42           154          7.2           7.2                0.82
43            97          7.2          10.3                0.70
44            70          7.3          10.5                0.72
45            93          7.2           9.2                0.72
46            80          7.3          10.2                0.71
47            98          7.3           9.7                0.72
48            87          7.3          10.1                0.72
49            66          5.8           8.7                0.73
50            65          6.0           8.2                0.71
51            58          6.0           7.5                0.72
52            59          5.9           8.0                0.72
53            60          6.0           8.4                0.74
54            58          6.1           8.5                0.71
55            58          6.3           7.7                0.72
56            58          5.9           8.1                0.73
57            76          6.5           8.5                0.72
58            59          6.1           8.1                0.70

Get Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, stratify=y, random_state=2529) 

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((41, 4), (18, 4), (41,), (18,))

GEt Model Tarin

In [ ]:

from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression(max_iter =500)

In [ ]:
model.fit(x_train,y_train)

LogisticRegression(max_iter=500)

Get Model Prediction

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
y_pred.shape

(18,)

In [ ]:
y_pred

array([2, 3, 2, 2, 1, 3, 3, 3, 2, 2, 1, 1, 3, 1, 2, 2, 2, 2])

Get Probability Of Each Predicted class

In [ ]:
model.predict_proba(x_test)

array([[3.84951593e-01, 6.15048407e-01, 1.08576744e-13],
       [4.56211097e-03, 3.49807476e-03, 9.91939814e-01],
       [4.90241031e-01, 5.09660923e-01, 9.80458982e-05],
       [3.53465346e-01, 6.46220815e-01, 3.13839298e-04],
       [5.00279932e-01, 4.99534284e-01, 1.85784021e-04],
       [2.78197188e-03, 4.11146680e-03, 9.93106561e-01],
       [6.66946035e-04, 1.25712269e-04, 9.99207342e-01],
       [2.27561794e-03, 4.46959561e-03, 9.93254786e-01],
       [4.16160890e-01, 5.83035529e-01, 8.03580896e-04],
       [4.37040001e-01, 5.62632940e-01, 3.27059618e-04],
       [5.55428928e-01, 4.44138117e-01, 4.32954330e-04],
       [7.05113359e-01, 2.94879119e-01, 7.52192779e-06],
       [1.75275079e-02, 6.72214892e-03, 9.75750343e-01],
       [5.72969759e-01, 4.24234150e-01, 2.79609136e-03],
       [2.87855160e-01, 6.51947963e-01, 6.01968769e-02],
       [2.54215102e-01, 6.89271796e-01, 5.65131013e-02],
       [4.58132127e-01, 5.41819734e-01, 4.81390644e-05],
       [4.59442101e-01, 5.40002

Get Model Evaluation

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[4 2 0]
 [0 7 0]
 [0 0 5]]


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      0.67      0.80         6
           2       0.78      1.00      0.88         7
           3       1.00      1.00      1.00         5

    accuracy                           0.89        18
   macro avg       0.93      0.89      0.89        18
weighted avg       0.91      0.89      0.88        18



Get future perdictions

In [ ]:
df_new = df.sample(1)

In [ ]:
df_new

Fruit Category Fruit Name  Fruit Weight  Fruit Width  Fruit Length  \
32               2     Orange           164          7.2           7.0   

    Fruit Colour Score  
32                 0.8

In [ ]:
x_new = df_new[['Fruit Weight','Fruit Width','Fruit Length','Fruit Colour Score']]

In [ ]:
x_new.shape

(1, 4)

In [ ]:
y_pred_new = model.predict(x_new)

In [ ]:
y_pred_new

array([2])

In [ ]:
model.predict(x_new)

array([2])